from flask import Flask
from alembic import command
from alembic.config import Config

from app.application.services.background_executor import background_executor
from app.infrastructure.db.extensions import db
from app.infrastructure.db.models import ActiveConfig, ConfigProfile, Job, SchemaMapping
from app.presentation.web.controllers.api_config import api_config_bp
from app.presentation.web.controllers.api_jobs import api_jobs_bp
from app.presentation.web.controllers.api_schema import api_schema_bp
from app.presentation.web.controllers.pages import pages_bp
from app.presentation.web.controllers.sse import sse_bp
from app.shared.settings import Settings


def create_web_app() -> Flask:
    app = Flask(
        __name__,
        template_folder="../presentation/web/templates",
        static_folder="../presentation/web/static",
    )
    settings = Settings.from_env()
    app.config.update(settings.to_flask_config())

    db.init_app(app)

    app.register_blueprint(pages_bp)
    app.register_blueprint(api_config_bp)
    app.register_blueprint(api_jobs_bp)
    app.register_blueprint(api_schema_bp)
    app.register_blueprint(sse_bp)

    @app.get("/health")
    def health() -> dict:
        return {"status": "ok", "work_type": app.config.get("WORK_TYPE")}

    def _alembic_cfg() -> Config:
        cfg = Config("alembic.ini")
        cfg.set_main_option("sqlalchemy.url", app.config["SQLALCHEMY_DATABASE_URI"])
        return cfg

    @app.cli.command("db-upgrade")
    def db_upgrade() -> None:
        command.upgrade(_alembic_cfg(), "head")

    @app.cli.command("db-downgrade")
    def db_downgrade() -> None:
        command.downgrade(_alembic_cfg(), "-1")

    @app.cli.command("db-revision-autogen")
    def db_revision_autogen() -> None:
        command.revision(_alembic_cfg(), autogenerate=True, message="autogenerated")

    with app.app_context():
        # touch models so their metadata is registered
        _ = (ConfigProfile, ActiveConfig, Job, SchemaMapping)
        command.upgrade(_alembic_cfg(), "head")

    background_executor.start(app)
    return app
